[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
solc_version = "0.8.20"

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "icm-contracts/=lib/icm-contracts/",
    "@forge-std/=lib/icm-contracts/lib/forge-std/src/",
    "@mocks/=lib/icm-contracts/contracts/mocks/",
    "@subnet-evm/=lib/icm-contracts/contracts/subnet-evm/",
    "@teleporter/=lib/icm-contracts/contracts/teleporter/",
    "@utilities/=lib/icm-contracts/contracts/utilities/",
]

[rpc_endpoints]
fuji = "${C_CHAIN_RPC_URL}"
appchain = "${APP_CHAIN_RPC_URL}"

[etherscan]
fuji = { key = "${SNOWTRACE_API_KEY}", url = "https://api-testnet.snowtrace.io/api" }
